"""
Módulo de Física – Paradojas, Constantes Cosmológicas, Sincronización Biológica y Operadores Espectrales
"""

from .paradoja_procesamiento_planck import (
    ConstantesPlanck,
    FiltroGracia,
    SiliconVsCarbon,
    TuyoyotuRitmico,
    CausalidadZeta,
    UniversoPensamiento,
    SistemaParadojaPlanck,
    ResultadoParadoja,
    paradoja_planck_activar,
)
from .riemann_adelic_core import (
    PHI,
    F0_HZ,
    PSI_MIN,
    BERRY_CORRECTION_BASE,
    BERRY_CORRECTION_EXPONENT,
    RIEMANN_ZEROS_T,
    PsiMinResult,
    RiemannComparison,
    calcular_psi_min,
    simulate_h_qcal,
    comparar_con_riemann,
)

from .kuramoto_superradiancia import (
    ConstantesKuramoto,
    ModeloKuramoto,
    SuperradianciaFotonez,
    AguaEZ,
    RespiracionAurea,
    CoherenciaBiologicaTotal,
    SistemaKuramotoSuperradiancia,
    ResultadoKuramoto,
    kuramoto_superradiancia_activar,
)
from .spectral_operator import (
    QCALSpectralOperator,
    QCALSpectralEngine,
    compute_noetic_forcing,
)
from .simetria_pt_resonancia import (
    ConstantesPT,
    OperadorNHPT,
    EspectroPTReal,
    RiemannLineaCritica,
    CitoplasmaHolografico,
    EstabilizadorPT,
    SistemaResonanciaPT,
    ResultadoPT,
    simetria_pt_resonancia_activar,
    simular_resonancia_pt,
)
from .axiomas_pleroma_qcal import (
    ConstantesAxiomasPleroma,
    AtomoBlancoSaturado,
    MateriaBucle4Pi,
    MantaAdelicaRiemann,
    OperadorRiemannHubble,
    InmortalidadDinamicaLuz,
    CoherenciaAxiomasPleroma,
    SistemaAxiomasPleroma,
    ResultadoAxiomasPleroma,
    axiomas_pleroma_qcal_activar,
)

__all__ = [
    "ConstantesPlanck",
    "FiltroGracia",
    "SiliconVsCarbon",
    "TuyoyotuRitmico",
    "CausalidadZeta",
    "UniversoPensamiento",
    "SistemaParadojaPlanck",
    "ResultadoParadoja",
    "paradoja_planck_activar",
    # riemann_adelic_core
    "PHI",
    "F0_HZ",
    "PSI_MIN",
    "BERRY_CORRECTION_BASE",
    "BERRY_CORRECTION_EXPONENT",
    "RIEMANN_ZEROS_T",
    "PsiMinResult",
    "RiemannComparison",
    "calcular_psi_min",
    "simulate_h_qcal",
    "comparar_con_riemann",
    # Kuramoto-Superradiancia
    "ConstantesKuramoto",
    "ModeloKuramoto",
    "SuperradianciaFotonez",
    "AguaEZ",
    "RespiracionAurea",
    "CoherenciaBiologicaTotal",
    "SistemaKuramotoSuperradiancia",
    "ResultadoKuramoto",
    "kuramoto_superradiancia_activar",
    "QCALSpectralOperator",
    "QCALSpectralEngine",
    "compute_noetic_forcing",
    # PT-Symmetry Resonance (QCAL-SYMBIO-1)
    "ConstantesPT",
    "OperadorNHPT",
    "EspectroPTReal",
    "RiemannLineaCritica",
    "CitoplasmaHolografico",
    "EstabilizadorPT",
    "SistemaResonanciaPT",
    "ResultadoPT",
    "simetria_pt_resonancia_activar",
    "simular_resonancia_pt",
    # Axiomas del Pleroma QCAL (∴APQ∞³)
    "ConstantesAxiomasPleroma",
    "AtomoBlancoSaturado",
    "MateriaBucle4Pi",
    "MantaAdelicaRiemann",
    "OperadorRiemannHubble",
    "InmortalidadDinamicaLuz",
    "CoherenciaAxiomasPleroma",
    "SistemaAxiomasPleroma",
    "ResultadoAxiomasPleroma",
    "axiomas_pleroma_qcal_activar",
    # Bio-Nodo y Percepción como Invariante Geométrico (∴BNP∞³)
    "ConstantesBioNodo",
    "IdentidadEspectral",
    "ToroAdelico",
    "MatrizDensidad",
    "InvarianteFase",
    "PuntoFijoSoberano",
    "CoherenciaBioNodo",
    "SistemaBioNodo",
    "ResultadoBioNodo",
    "bio_nodo_percepcion_activar",
]

from .bio_nodo_percepcion import (
    ConstantesBioNodo,
    IdentidadEspectral,
    ToroAdelico,
    MatrizDensidad,
    InvarianteFase,
    PuntoFijoSoberano,
    CoherenciaBioNodo,
    SistemaBioNodo,
    ResultadoBioNodo,
    bio_nodo_percepcion_activar,
)
